#ifdef KEY_VALUES_INCLUDE

#if false // Need it for formatting
namespace Kepler{}
#endif

std::string keys[] = {
    "",                // 0
    "",                // 1
    "",                // 2
    "",                // 3
    "",                // 4
    "",                // 5
    "",                // 6
    "",                // 7
    "",                // 8
    "ESCAPE",          // 9
    "1",               // 10
    "2",               // 11
    "3",               // 12
    "4",               // 13
    "5",               // 14
    "6",               // 15
    "7",               // 16
    "8",               // 17
    "9",               // 18
    "0",               // 19
    "MINUS",           // 20
    "PLUS",            // 21
    "BACKSPACE",       // 22
    "TAB",             // 23
    "Q",               // 24
    "W",               // 25
    "E",               // 26
    "R",               // 27
    "T",               // 28
    "Y",               // 29
    "U",               // 30
    "I",               // 31
    "O",               // 32
    "P",               // 33
    "BRACKET_LEFT",    // 34
    "BRACKET_RIGHT",   // 35
    "ENTER",           // 36
    "CONTROL_LEFT",    // 37
    "A",               // 38
    "S",               // 39
    "D",               // 40
    "F",               // 41
    "G",               // 42
    "H",               // 43
    "J",               // 44
    "K",               // 45
    "L",               // 46
    "SEMICOLON",       // 47
    "APOSTROPHE",      // 48
    "TILDE",           // 49
    "SHIFT_LEFT",      // 50
    "BACKSLASH",       // 51
    "Z",               // 52
    "X",               // 53
    "C",               // 54
    "V",               // 55
    "B",               // 56
    "N",               // 57
    "M",               // 58
    "COMMA",           // 59
    "PERIOD",          // 60
    "SLASH",           // 61
    "SHIFT_RIGHT",     // 62
    "NUMPAD_ASTERISK", // 63
    "ALT_LEFT",        // 64
    "SPACE",           // 65
    "CAPSLOCK",        // 66
    "F1",              // 67
    "F2",              // 68
    "F3",              // 69
    "F4",              // 70
    "F5",              // 71
    "F6",              // 72
    "F7",              // 73
    "F8",              // 74
    "F9",              // 75
    "F10",             // 76
    "NUM_LOCK",        // 77
    "SCROLL_LOCK",     // 78
    "NUMPAD_7",        // 79
    "NUMPAD_8",        // 80
    "NUMPAD_9",        // 81
    "NUMPAD_MINUS",    // 82
    "NUMPAD_4",        // 83
    "NUMPAD_5",        // 84
    "NUMPAD_6",        // 85
    "NUMPAD_PLUS",     // 86
    "NUMPAD_1",        // 87
    "NUMPAD_2",        // 88
    "NUMPAD_3",        // 89
    "NUMPAD_0",        // 90
    "NUMPAD_PERIOD",   // 91
    "",                // 92
    "",                // 93
    "",                // 94
    "F11",             // 95
    "F12",             // 96
    "",                // 97
    "",                // 98
    "",                // 99
    "",                // 100
    "",                // 101
    "",                // 102
    "",                // 103
    "NUMPAD_ENTER",    // 104
    "CONTROL_RIGHT",   // 105
    "NUMPAD_SLASH",    // 106
    "",                // 107
    "ALT_RIGHT",       // 108
    "",                // 109
    "HOME",            // 110
    "ARROW_UP",        // 111
    "PAGE_UP",         // 112
    "ARROW_LEFT",      // 113
    "ARROW_RIGHT",     // 114
    "END",             // 115
    "ARROW_DOWN",      // 116
    "PAGE_DOWN",       // 117
    "INSERT",          // 118
    "DELETE",          // 119
    "",                // 120
    "",                // 121
    "",                // 122
    "",                // 123
    "",                // 124
    "",                // 125
    "",                // 126
    "",                // 127
    "",                // 128
    "",                // 129
    "",                // 130
    "",                // 131
    "",                // 132
    "",                // 133
    "",                // 134
    "",                // 135
    "",                // 136
    "",                // 137
    "",                // 138
    "",                // 139
    "",                // 140
};

#endif
