# This file is generated by gyp; do not edit.

TOOLSET := target
TARGET := kepler-glfw-native
DEFS_Debug := \
	'-DNODE_GYP_MODULE_NAME=kepler-glfw-native' \
	'-DUSING_UV_SHARED=1' \
	'-DUSING_V8_SHARED=1' \
	'-DV8_DEPRECATION_WARNINGS=1' \
	'-D_LARGEFILE_SOURCE' \
	'-D_FILE_OFFSET_BITS=64' \
	'-D_GLFW_X11' \
	'-DDEBUG' \
	'-D_DEBUG' \
	'-DV8_ENABLE_CHECKS'

# Flags passed to all source files.
CFLAGS_Debug := \
	-fPIC \
	-pthread \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-m64 \
	-g \
	-O0

# Flags passed to only C files.
CFLAGS_C_Debug :=

# Flags passed to only C++ files.
CFLAGS_CC_Debug := \
	-fno-rtti \
	-std=gnu++0x

INCS_Debug := \
	-I/home/brandon/.node-gyp/8.10.0/include/node \
	-I/home/brandon/.node-gyp/8.10.0/src \
	-I/home/brandon/.node-gyp/8.10.0/deps/openssl/config \
	-I/home/brandon/.node-gyp/8.10.0/deps/openssl/openssl/include \
	-I/home/brandon/.node-gyp/8.10.0/deps/uv/include \
	-I/home/brandon/.node-gyp/8.10.0/deps/zlib \
	-I/home/brandon/.node-gyp/8.10.0/deps/v8/include \
	-I/home/brandon/Documents/GitHub/kepler-glfw/node_modules/node-addon-api \
	-I$(srcdir)/../../kepler-glfw/glfw/include

DEFS_Release := \
	'-DNODE_GYP_MODULE_NAME=kepler-glfw-native' \
	'-DUSING_UV_SHARED=1' \
	'-DUSING_V8_SHARED=1' \
	'-DV8_DEPRECATION_WARNINGS=1' \
	'-D_LARGEFILE_SOURCE' \
	'-D_FILE_OFFSET_BITS=64' \
	'-D_GLFW_X11'

# Flags passed to all source files.
CFLAGS_Release := \
	-fPIC \
	-pthread \
	-Wall \
	-Wextra \
	-Wno-unused-parameter \
	-m64 \
	-O3 \
	-fno-omit-frame-pointer

# Flags passed to only C files.
CFLAGS_C_Release :=

# Flags passed to only C++ files.
CFLAGS_CC_Release := \
	-fno-rtti \
	-std=gnu++0x

INCS_Release := \
	-I/home/brandon/.node-gyp/8.10.0/include/node \
	-I/home/brandon/.node-gyp/8.10.0/src \
	-I/home/brandon/.node-gyp/8.10.0/deps/openssl/config \
	-I/home/brandon/.node-gyp/8.10.0/deps/openssl/openssl/include \
	-I/home/brandon/.node-gyp/8.10.0/deps/uv/include \
	-I/home/brandon/.node-gyp/8.10.0/deps/zlib \
	-I/home/brandon/.node-gyp/8.10.0/deps/v8/include \
	-I/home/brandon/Documents/GitHub/kepler-glfw/node_modules/node-addon-api \
	-I$(srcdir)/../../kepler-glfw/glfw/include

OBJS := \
	$(obj).target/$(TARGET)/../../kepler-glfw/glfw/src/context.o \
	$(obj).target/$(TARGET)/../../kepler-glfw/glfw/src/init.o \
	$(obj).target/$(TARGET)/../../kepler-glfw/glfw/src/input.o \
	$(obj).target/$(TARGET)/../../kepler-glfw/glfw/src/monitor.o \
	$(obj).target/$(TARGET)/../../kepler-glfw/glfw/src/vulkan.o \
	$(obj).target/$(TARGET)/../../kepler-glfw/glfw/src/window.o \
	$(obj).target/$(TARGET)/../../kepler-glfw/glfw/src/x11_init.o \
	$(obj).target/$(TARGET)/../../kepler-glfw/glfw/src/x11_monitor.o \
	$(obj).target/$(TARGET)/../../kepler-glfw/glfw/src/x11_window.o \
	$(obj).target/$(TARGET)/../../kepler-glfw/glfw/src/xkb_unicode.o \
	$(obj).target/$(TARGET)/../../kepler-glfw/glfw/src/posix_time.o \
	$(obj).target/$(TARGET)/../../kepler-glfw/glfw/src/posix_thread.o \
	$(obj).target/$(TARGET)/../../kepler-glfw/glfw/src/glx_context.o \
	$(obj).target/$(TARGET)/../../kepler-glfw/glfw/src/egl_context.o \
	$(obj).target/$(TARGET)/../../kepler-glfw/glfw/src/osmesa_context.o \
	$(obj).target/$(TARGET)/../../kepler-glfw/glfw/src/linux_joystick.o

# Add to the list of files we specially track dependencies for.
all_deps += $(OBJS)

# Make sure our dependencies are built before any of us.
$(OBJS): | $(builddir)/nothing.a $(obj).target/../../kepler-glfw/node_modules/node-addon-api/src/nothing.a

# CFLAGS et al overrides must be target-local.
# See "Target-specific Variable Values" in the GNU Make manual.
$(OBJS): TOOLSET := $(TOOLSET)
$(OBJS): GYP_CFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_C_$(BUILDTYPE))
$(OBJS): GYP_CXXFLAGS := $(DEFS_$(BUILDTYPE)) $(INCS_$(BUILDTYPE))  $(CFLAGS_$(BUILDTYPE)) $(CFLAGS_CC_$(BUILDTYPE))

# Suffix rules, putting all outputs into $(obj).

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(srcdir)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# Try building from generated source, too.

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj).$(TOOLSET)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

$(obj).$(TOOLSET)/$(TARGET)/%.o: $(obj)/%.c FORCE_DO_CMD
	@$(call do_cmd,cc,1)

# End of this set of suffix rules
### Rules for final target.
LDFLAGS_Debug := \
	-pthread \
	-rdynamic \
	-m64

LDFLAGS_Release := \
	-pthread \
	-rdynamic \
	-m64

LIBS := \
	-lX11

$(obj).target/../../kepler-glfw/kepler-glfw-native.so: GYP_LDFLAGS := $(LDFLAGS_$(BUILDTYPE))
$(obj).target/../../kepler-glfw/kepler-glfw-native.so: LIBS := $(LIBS)
$(obj).target/../../kepler-glfw/kepler-glfw-native.so: LD_INPUTS := $(OBJS) $(obj).target/../../kepler-glfw/node_modules/node-addon-api/src/nothing.a
$(obj).target/../../kepler-glfw/kepler-glfw-native.so: TOOLSET := $(TOOLSET)
$(obj).target/../../kepler-glfw/kepler-glfw-native.so: $(OBJS) $(obj).target/../../kepler-glfw/node_modules/node-addon-api/src/nothing.a FORCE_DO_CMD
	$(call do_cmd,solink)

all_deps += $(obj).target/../../kepler-glfw/kepler-glfw-native.so
# Add target alias
.PHONY: kepler-glfw-native
kepler-glfw-native: $(builddir)/kepler-glfw-native.so

# Copy this to the shared library output path.
$(builddir)/kepler-glfw-native.so: TOOLSET := $(TOOLSET)
$(builddir)/kepler-glfw-native.so: $(obj).target/../../kepler-glfw/kepler-glfw-native.so FORCE_DO_CMD
	$(call do_cmd,copy)

all_deps += $(builddir)/kepler-glfw-native.so
# Short alias for building this shared library.
.PHONY: kepler-glfw-native.so
kepler-glfw-native.so: $(obj).target/../../kepler-glfw/kepler-glfw-native.so $(builddir)/kepler-glfw-native.so

# Add shared library to "all" target.
.PHONY: all
all: $(builddir)/kepler-glfw-native.so

